copy announce.h TCPIP\announce.h
copy arp.c TCPIP\arp.c
copy arp.h TCPIP\arp.h
copy AutoIP.h TCPIP\AutoIP.h
copy BerkeleyAPI.h TCPIP\BerkeleyAPI.h
copy BigInt.h TCPIP\BigInt.h
copy Delay.c TCPIP\Delay.c
copy Delay.h TCPIP\Delay.h
copy DHCP.h TCPIP\DHCP.h
copy DNS.h TCPIP\DNS.h
copy ENC28J60.c TCPIP\ENC28J60.c
copy ENC28J60.h TCPIP\ENC28J60.h
copy Helpers.c TCPIP\Helpers.c
copy Helpers.h TCPIP\Helpers.h
copy HTTP.h TCPIP\HTTP.h
copy ICMP.c TCPIP\ICMP.c
copy ICMP.h TCPIP\ICMP.h
copy IP.c TCPIP\IP.c
copy IP.h TCPIP\IP.h
copy MAC.h TCPIP\MAC.h
copy MPFS.h TCPIP\MPFS.h
copy MPFS2.h TCPIP\MPFS2.h
copy SNTP.c TCPIP\SNTP.c
copy SNTP.h TCPIP\SNTP.h
copy StackTsk.c TCPIP\StackTsk.c
copy StackTsk.h TCPIP\StackTsk.h
copy TCP.h TCPIP\TCP.h
copy TCPIP.h TCPIP\TCPIP.h
copy TCPIP_ENC28.h TCPIP\TCPIP_ENC28.h
copy Telnet.h TCPIP\Telnet.h
copy Tick.c TCPIP\Tick.c
copy Tick.h TCPIP\Tick.h
copy UDP.c TCPIP\UDP.c
copy UDP.h TCPIP\UDP.h
pause
